export const ASSUMPTION_DEFAULTS = Object.freeze({
  shiftMinutes: 75,
  maxSimulationMinutes: 180,
  beltTravelMinutes: 3,
  boxLineRatePerHour: 900,
  jiffyLineRatePerHour: 1350,
  aisleCapacityItems: 200,
  excellentRatePerHour: 450,
  goodRatePerHour: 325,
  lowRatePerHour: 250,
  safeWipPerStower: 15,
  safeWipFloor: 50,
  basePenaltyThreshold: 0.65,
  minPenaltyThreshold: 0.2,
  oversizeBaselineRatio: 1 / 36,
  thresholdDropScale: 0.0223,
  thresholdDropAmount: 0.15,
  boxPenaltyMultiplier: 2,
  objectiveTimeWeight: 1000,
  objectiveUnstowedWeight: 1000,
  objectiveUnfinishedPenalty: 180000,
  searchWindowBuffer: 15,
  searchCap: 150,
  searchStepThreshold: 50,
  searchStepLarge: 2,
});

export const ASSUMPTION_FIELDS = Object.freeze([
  {
    key: 'shiftMinutes',
    group: 'Time and Belt Flow',
    label: 'Target Shift Minutes',
    min: 15,
    max: 240,
    step: 1,
    description: 'Minutes used for throughput guidance and staffing recommendation.',
  },
  {
    key: 'maxSimulationMinutes',
    group: 'Time and Belt Flow',
    label: 'Simulation Cutoff Minutes',
    min: 30,
    max: 480,
    step: 1,
    description: 'Hard stop for infeasible scenarios before marking failure.',
  },
  {
    key: 'beltTravelMinutes',
    group: 'Time and Belt Flow',
    label: 'Belt Travel Minutes',
    min: 1,
    max: 15,
    step: 1,
    description: 'Average travel time from belt drop to stow floor.',
  },
  {
    key: 'boxLineRatePerHour',
    group: 'Time and Belt Flow',
    label: 'Box Line Rate (items/hr)',
    min: 60,
    max: 3600,
    step: 10,
    description: 'How many BOXES does the main induct process per hour?',
  },
  {
    key: 'jiffyLineRatePerHour',
    group: 'Time and Belt Flow',
    label: 'Jiffy Line Rate (items/hr)',
    min: 60,
    max: 4800,
    step: 10,
    description: 'How many JIFFIES does the jiffy line process per hour?',
  },
  {
    key: 'aisleCapacityItems',
    group: 'Time and Belt Flow',
    label: 'Aisle Buffer Capacity',
    min: 50,
    max: 500,
    step: 5,
    description: 'Maximum stowable package count assumed per active aisle.',
  },
  {
    key: 'excellentRatePerHour',
    group: 'Capacity and Staffing Physics',
    label: 'Excellent Stower Rate (items/hr)',
    min: 60,
    max: 1200,
    step: 5,
    description: 'Average stow speed for strong performers.',
  },
  {
    key: 'goodRatePerHour',
    group: 'Capacity and Staffing Physics',
    label: 'Good Stower Rate (items/hr)',
    min: 60,
    max: 1200,
    step: 5,
    description: 'Average stow speed for average/good performers.',
  },
  {
    key: 'lowRatePerHour',
    group: 'Capacity and Staffing Physics',
    label: 'Low Stower Rate (items/hr)',
    min: 30,
    max: 1200,
    step: 5,
    description: 'Average stow speed for newer or weaker performers.',
  },
  {
    key: 'safeWipPerStower',
    group: 'Capacity and Staffing Physics',
    label: 'Safe WIP per Stower',
    min: 1,
    max: 40,
    step: 0.5,
    description: 'Safety threshold multiplier to trigger automatic belt pauses.',
  },
  {
    key: 'safeWipFloor',
    group: 'Capacity and Staffing Physics',
    label: 'Minimum Safe WIP Floor',
    min: 1,
    max: 300,
    step: 1,
    description: 'Fallback safety limit used if staffing count is zero.',
  },
  {
    key: 'basePenaltyThreshold',
    group: 'Penalty and Threshold Behavior',
    label: 'Base Penalty Threshold',
    min: 0.1,
    max: 0.95,
    step: 0.01,
    description: 'Utilization trigger where box stow penalty starts.',
  },
  {
    key: 'minPenaltyThreshold',
    group: 'Penalty and Threshold Behavior',
    label: 'Minimum Penalty Threshold',
    min: 0.05,
    max: 0.9,
    step: 0.01,
    description: 'Lower bound for oversize-adjusted penalty threshold.',
  },
  {
    key: 'oversizeBaselineRatio',
    group: 'Penalty and Threshold Behavior',
    label: 'Oversize Baseline Ratio',
    min: 0,
    max: 0.5,
    step: 0.001,
    description: 'Reference oversize mix used before threshold penalties scale.',
  },
  {
    key: 'thresholdDropScale',
    group: 'Penalty and Threshold Behavior',
    label: 'Threshold Drop Scale',
    min: 0.001,
    max: 1,
    step: 0.001,
    description: 'Controls how quickly threshold drops as oversize ratio rises.',
  },
  {
    key: 'thresholdDropAmount',
    group: 'Penalty and Threshold Behavior',
    label: 'Threshold Drop Amount',
    min: 0.01,
    max: 1,
    step: 0.01,
    description: 'Penalty reduction amplitude per threshold drop unit.',
  },
  {
    key: 'boxPenaltyMultiplier',
    group: 'Penalty and Threshold Behavior',
    label: 'Box Penalty Multiplier',
    min: 1,
    max: 5,
    step: 0.1,
    description: 'Cost multiplier applied to box stow speed after threshold.',
  },
  {
    key: 'objectiveTimeWeight',
    group: 'Optimization Search and Objective',
    label: 'Objective Time Weight',
    min: 1,
    max: 100000,
    step: 1,
    description: 'Weight applied to completion time in objective score.',
  },
  {
    key: 'objectiveUnstowedWeight',
    group: 'Optimization Search and Objective',
    label: 'Objective Unstowed Weight',
    min: 1,
    max: 100000,
    step: 1,
    description: 'Weight applied to unfinished volume in objective score.',
  },
  {
    key: 'objectiveUnfinishedPenalty',
    group: 'Optimization Search and Objective',
    label: 'Objective Unfinished Penalty',
    min: 0,
    max: 2000000,
    step: 100,
    description: 'Extra penalty applied when scenario remains unfinished.',
  },
  {
    key: 'searchWindowBuffer',
    group: 'Optimization Search and Objective',
    label: 'Search Window Buffer Minutes',
    min: 0,
    max: 200,
    step: 1,
    description: 'Extra minute window added around expected search boundary.',
  },
  {
    key: 'searchCap',
    group: 'Optimization Search and Objective',
    label: 'Search Cap Minutes',
    min: 10,
    max: 600,
    step: 1,
    description: 'Absolute maximum explored phase transition minute.',
  },
  {
    key: 'searchStepThreshold',
    group: 'Optimization Search and Objective',
    label: 'Large Step Threshold',
    min: 1,
    max: 500,
    step: 1,
    description: 'Use larger search step once search range exceeds this value.',
  },
  {
    key: 'searchStepLarge',
    group: 'Optimization Search and Objective',
    label: 'Large Search Step',
    min: 1,
    max: 20,
    step: 1,
    description: 'Step size used during large search ranges.',
  },
]);

export const ASSUMPTION_GROUPS = Object.freeze([
  'Time and Belt Flow',
  'Capacity and Staffing Physics',
  'Penalty and Threshold Behavior',
  'Optimization Search and Objective',
]);

export const ASSUMPTION_RULES = Object.freeze(
  ASSUMPTION_FIELDS.reduce((acc, field) => {
    acc[field.key] = { min: field.min, max: field.max };
    return acc;
  }, {})
);
