export const SCENARIO_PRESETS = Object.freeze([
  {
    id: 'light',
    label: 'Light Day',
    description: '~2,500 packages, small crew',
    icon: '☀️',
    values: {
      totalBoxes: 800,
      totalJiffies: 1700,
      excellent: 1,
      good: 2,
      bad: 1,
      aisles: 8,
      ratioBoxOV: 1,
      ratioBoxBig: 10,
      ratioBoxMed: 25,
      ratioJiffySB: 1,
      ratioJiffyJif: 5,
    },
  },
  {
    id: 'standard',
    label: 'Standard SSD',
    description: '~4,500 packages, balanced crew',
    icon: '📦',
    values: {
      totalBoxes: 1500,
      totalJiffies: 3000,
      excellent: 2,
      good: 3,
      bad: 1,
      aisles: 10,
      ratioBoxOV: 1,
      ratioBoxBig: 10,
      ratioBoxMed: 25,
      ratioJiffySB: 1,
      ratioJiffyJif: 5,
    },
  },
  {
    id: 'heavy',
    label: 'Heavy Volume',
    description: '~8,000 packages, large crew',
    icon: '🔥',
    values: {
      totalBoxes: 3000,
      totalJiffies: 5000,
      excellent: 3,
      good: 5,
      bad: 2,
      aisles: 14,
      ratioBoxOV: 1,
      ratioBoxBig: 12,
      ratioBoxMed: 20,
      ratioJiffySB: 2,
      ratioJiffyJif: 6,
    },
  },
  {
    id: 'oversize',
    label: 'Oversize-Heavy',
    description: '~4,000 packages, high OV ratio',
    icon: '📐',
    values: {
      totalBoxes: 2000,
      totalJiffies: 2000,
      excellent: 2,
      good: 4,
      bad: 2,
      aisles: 12,
      ratioBoxOV: 8,
      ratioBoxBig: 10,
      ratioBoxMed: 15,
      ratioJiffySB: 1,
      ratioJiffyJif: 4,
    },
  },
]);
